### ISSUE TITLE
Passing container props to wrapped component

### ISSUE THREAD

**Issue by vonubisch** [GeekyAnts/firestore-react#1]
When passing props to the container they are not getting passed along to the wrapped component. I think on line `72` in `dist/index.js` you need to merge with `this.props` instead of `{}`:

```
return React.createElement(WrappedComponent, __assign(this.props, this.state.results));
```

**Comment by sanketsahusoft** [comment]
Thanks for pointing! I just fixed it with the latest version `firestore-react@0.1.5`
