### ISSUE TITLE
Error in installing dependencies using npm

### ISSUE THREAD

**Issue by GeekRishabh** [GeekyAnts/firestore-react#2]
## How to Reproduce this 
 • Clone repo 
 • `git clone https://github.com/GeekyAnts/firestore-react.git` 
 • `cd firestore-react`
 and then run `npm install`

![screen shot 2018-01-04 at 6 35 05 pm](https://user-images.githubusercontent.com/23093075/34564765-080c3da0-f17e-11e7-8361-19a08b087db7.png)

**Comment by sanketsahusoft** [comment]
The root isn't a standalone project. Use examples/simple-list to test the library.

I can discuss this offline too if needed.
